### ISSUE TITLE
Copy string with special characters

### ISSUE THREAD

**Issue by ghost** [trwyant/perl-Mac-Pasteboard#1] opened 2021-02-20 14:18 UTC
Setting 

```
my $CLIP = Mac::Pasteboard->new();
Mac::Pasteboard->set (encode => 1);
my ($data, $flags) = $CLIP->paste ();
```

encode => 1 does not seem to affect the ability to get the text from the Pasteboard and manipulate it if characters like üä are in the string

**Comment by trwyant** [comment] 2021-02-21 23:42
Thanks for the report.

This module has not gotten much love of late, partly because Apple keeps changing their preferred interface. This will take some looking-into, I'm afraid.

**Comment by trwyant** [comment] 2021-02-22 02:31
As of now, it looks like something may be going on with the encode functionality. And it may be that the default text flavor is ill-chosen, or at least inappropriate for characters outside the ASCII range.

What happens if you do

`my ( $data, $flags ) = $CLIP->paste( 'public.utf8-plain-text' );`

To ensure I am reproducing your problem correctly, could you come up with one non-ASCII character that demonstrates the problem, let me know what it is (I'm using LATIN CAPITAL LETTER AE at the moment) and if possible how it was encoded onto the clipboard? The output of the `pbtool `command `flavors` might be useful information here.

While I'm thinking of it, what version of macOS are you running? This module stopped playing nicely with pbcopy/pbpaste when Catalina (macOS 10.16) came out, and in a semi-panic I slapped a band-aid on it by having `copy()` spawn `pbcopy` under that version. But the problem there may also have been a flavor/encoding problem. And at this point I am pretty sure the Catalina-or-later functionality does not encode the data properly onto the clipboard.

If you are under Catalina or later you can try setting environment variable `MAC_PASTEBOARD_USE_PBCOPY` to `0` (that is a zero, not a letter 'O'), to disable the use of the `pbcopy` program. You can also try using the default flavor and then hand-decoding the data with something like

```
use Encode;

...

my ( $data, $flags ) = $CLIP->paste();
$data = decode( 'UTF-8', $data );
```

I will continue to work on this when and as I can. Please let me know anything further you find out.

**Comment by trwyant** [comment] 2021-02-22 05:54
After fiddling for a bit, here is what I think is worth trying:

```
use Mac::Pasteboard;
$Mac::Pasteboard::USE_PBCOPY = 0; # In lieu of the environment variable

my $CLIP = Mac::Pasteboard->new();
$CLIP->set(
    encode => 1,
    default_flavor => 'public.utf8-plain-text',
);

my ( $data, $flags ) = $CLIP->paste();
```

It looks like all I really needed to do for Catalina is change the default flavor. And maybe default `encode` to a true value.

Both `$Mac::Pasteboard::USE_PBCOPY` and environment variable `MAC_PASTEBOARD_USE_PBCOPY` are "officially" undocumented and unsupported. Between you and me (and whoever else reads this) they will retain their current function (controlling whether the `pbcopy` executable is spawned to put stuff on the pasteboard) at least for the next release, though the default will be not to use `pbcopy` even under Catalina.

**Comment by trwyant** [comment] 2021-02-22 06:34
But I'm still not sure the above interoperates completely with pbcopy/pbpaste. Maybe if I sleep on it things will become clearer.

**Comment by trwyant** [comment] 2021-02-23 03:03
Verslon 0.012_01 (Git comit 8fe9193, tag v00.012_01) just went to PAUSE. The Changes file has a bunch of stuff, but the short version is that under macOS 10.15 Catalina and above, the default data flavor is now public.utf8-plain-text and the default 'encode' attribute is now true. These are unchanged before Catalina, at least partly because I do not have such a system available for testing.

These, plus making sure the proper encoding/decoding takes place wherever data go into or out of the building. This is what the problem was as of my previous post.

The `$Mac::Pasteboard::USE_PBCOPY` variable and `MAC_PASTEBOARD_USE_PBCOPY` environment variables are still in the code, but are now always taken as false, and should not be used.

Please take a look at the revised module and see if it fixes your problem. Unless either you or the CPAN testers find a problem I will probably do a production release in a week or so.

**Comment by trwyant** [comment] 2021-03-02 22:33
Production code just went to PAUSE. If nothing turns up in a week I will close this ticket.

Thanks again for reporting this.

**Closed as completed** 2021-03-28 02:20 UTC
